
<footer class="container" style="margin-bottom:0px">


    <nav class="navbar navbar-inverse navbar-bottom cor-barra-fim">


         <div class="container">

                <div class="row">

                    <div class="col-md-1">

                    </div>


                        <div class="col-sm-3" style=": 0 0 0 0px">


                            <h3 id="footer-header">D&uacute;vidas e Suporte:</h3>



                                <p><a href="<?php echo BASE . 'estatico/entrega
                                '; ?>" id="config-links">Entrega</a></p>
                                <p><a href="<?php echo BASE . 'estatico/formas-pagamento'; ?>" id="config-links">Formas de Pagamento</a></p>
                                <p><a href="<?php echo BASE . 'estatico/garantia'; ?>" id="config-links">Garantia</a></p>
                                <p><a href="<?php echo BASE . 'estatico/politica-privacidade'; ?>" id="config-links">Pol&iacute;tica de Privacidade</a></p>
                                <p><a href="<?php echo BASE . 'estatico/troca'; ?>" id="config-links">Trocas e Devolu&ccedil;&otilde;es</a></p>


                        </div>

                        <div class="col-sm-3" style="padding: 0 0 0 0px">


                            <h3 id="footer-header">Institucional:</h3>


                                <p><a href="<?php echo BASE . 'estatico/quem-somos'; ?>" id="config-links">Quem Somos</a></p>
                                <p><a href="<?php echo BASE . 'estatico/missao'; ?>" id="config-links">Miss&atilde;o, Vis&atilde;o e Valores</a></p>





                                <h3 id="footer-header titulo-cor-fim">Atendimento:</h3>
                                <b>Segunda a Sexta:</b> <p>Das 9h &aacute;s 19h</p>
                                <b>S&aacute;bado:</b> <p>Das 13h &aacute;s 18h</p>


                    </div>

                            <p></p>


                    <div class="col-md-5" style="padding: 0 0 0 0px">

                        <h3 id="footer-header">Curta a AGP no Facebook:</h3>

                        <iframe src="https://www.facebook.com/plugins/page.php?href=https%3A%2F%2Fwww.facebook.com%2FAGP-Performance-Shop-1066712673424628&tabs=timeline&width=340&height=500&small_header=false&adapt_container_width=true&hide_cover=false&show_facepile=true&appId" width="500" height="400" style="border:none;overflow:hidden" frameborder="0" allowTransparency="true"></iframe>


                   </div>

            </div>



        </div>


        <br>



        <aside class="col-md-12">

            <div class="panel panel-default dados-empresa">


                    <div class="panel-heading">


                            <h3 class="panel-title dados-fonte-titulo"><center>AGP Performance Shop <?php echo date("Y"); ?> - Todos os direitos reservados.   CNPJ: 09.386.496/0001-03 </center> </h3>

                    </div>


                    <div class="panel-body dados-fonte"> <b>Endere&ccedil;o:</b> R. da Grota, 483 - Tucuruvi <p>CEP: 02206-010 &ndash; S&atilde;o Paulo/SP </div>
                    <div class="panel-body dados-fonte-condicoes"> Condi&ccedil;&otilde;es: <p>***Pre&ccedil;os e condi&ccedil;&otilde;es de pagamento exclusivos para compras via internet. N&atilde;o Possu&iacute;mos Loja ou Lojas F&iacute;sicas. Os pre&ccedil;os anunciados neste site podem ser alterados sem pr&eacute;vio aviso. A AGP Performance Shop, n&atilde;o &eacute; respons&aacute;vel por erros descritivos. As fotos contidas nesta p&aacute;gina s&atilde;o meramente ilustrativas do produto e podem variar de acordo com o fornecedor/lote do fabricante. Ofertas v&aacute;lidas at&eacute; o t&eacute;rmino de nossos estoques. Vendas sujeitas &agrave; an&aacute;lise e confirma&ccedil;&atilde;o de dados. </div>



                    </div>
            </div>


        </aside>



</nav>
</footer>







        </section>


</body>
</html>
