<!doctype html>
<html lang="pt-br">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title><?php echo $view_title; ?></title>
  <link rel="shortcut icon" href="<?php echo IMG; ?>agp.ico" type="image/x-icon">
  <link rel="stylesheet" href="<?php echo BOWER; ?>bootstrap/css/bootstrap.min.css" type="text/css">
  <link rel="stylesheet" href="<?php echo BOWER; ?>font-awesome/css/font-awesome.min.css" type="text/css">
  <link rel="stylesheet" href="<?php echo CSS; ?>cor.css" type="text/css">

  <script src="<?php echo BOWER; ?>bootstrap/js/jquery.js"></script>
  <script src="<?php echo BOWER; ?>bootstrap/js/bootstrap.min.js"></script>
  <?php 
  echo $add_css;
  echo $add_js;
  ?>
</head>
<!-- Barra de Navegação Superior -->
<nav class="navbar navbar-inverse fundo-barra">
  <div class="container">


    <div class="navbar-header cor-barra">

      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-

      collapse-1" aria-expanded="false">

      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>


    <div class="navbar-header navbar-left">
      <a href="<?php  echo BASE. 'lista-produtos'; ?>">
        <img class="img-responsive" src="<?php echo IMG; ?>agplogo.png" alt="LOGO" width="225" height="200">
      </a>
    </div>

  </div>

  <div class="col-sm-2">
  </div>

  <form class="navbar-form navbar-left"  action="<?php echo BASE. 'lista-produtos/pesquisa/';  ?>" method="GET">
    <br>
    <div class="form-group">

      <input type="text" maxlength="60" class="form-control" style="min-width:300px;" placeholder="Pesquisa" name="barra">
    </div>
    <button type="submit" class="btn btn-default"><span class="glyphicon glyphicon-search" aria-

      hidden="true"></span></button>
    </form>

    <ul class="nav navbar-nav navbar-right">
      <br>
      <?php
      //if(isset($this->auth->getUserId()))
      $teste = $this->auth->getUserId();  
      if(is_null($teste)){
        echo '<li><a href="'.  BASE .'login">Login</a></li>';
        echo '<li><a href="'. BASE .'cadastro-cliente">Cadastro</a></li>';
      }
      else{
        $user = User::find($teste);
        echo  '<li><a href="'. BASE . 'conta">'. 'Olá, '.$user->name .'</a> </li><li>
        <a href="'. BASE . 'login/sair">Sair</a></li>';
      }

      unset($teste);
      ?>
      <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-

        expanded="false">Carrinho<span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li class="disabled"><a ><?php 

            function trim_value(&$value) 
            { 
              $value = trim($value); 
            }

            if(isset($_COOKIE['sec_session_id'])){

             $test = Cart::find_all_by_hash($_COOKIE['sec_session_id']);
             $soma = 0;
             $count = count($test);
             $qtdProdutos = 0;

             foreach ($test as $c) {
              $produto = Product::find($c->product_id);
              $soma = $soma + $produto->price * $c->amount;
              $qtdProdutos = $qtdProdutos + $c->amount;
            }



            echo $qtdProdutos; ?> Produto(s) no Carrinho</a></li>
            <li class="disabled"><a >Valor Total: R$ <?php echo number_format($soma, 2, ',', '.'); ?></a></li>
            <li><a href="<?php echo BASE. 'carrinho/detalhes'; ?>">Ir para o Carrinho</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="">Concluír Compra</a></li>
          </ul>
        </li>
      </ul>
      <?php 
    }
    else{
      ?>
      0 Produto(s) no Carrinho</a></li>
      <li class="disabled"><a >Valor Total: R$ <?php echo number_format(0, 2, ',', '.'); ?></a></li>
      <li><a href="<?php echo BASE. 'carrinho/detalhes'; ?>">Ir para o Carrinho</a></li>
      <li role="separator" class="divider"></li>
      <li><a href="<?php echo BASE . 'pedido/endereco-entrega' ;?>">Concluír Compra</a></li>
      <?php 

    } ?>
  </ul>  

</div>
<!-- /.container -->

</nav>
<!-- Fim do Cabeçalho -->

</header>
<!-- Começo do Codigo -->
<body>
