<!doctype html>
<html lang="pt-br">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title><?php echo $view_title; ?></title>
  <link rel="shortcut icon" href="<?php echo IMG; ?>agp.ico" type="image/x-icon">
  <link rel="stylesheet" href="<?php echo BOWER; ?>bootstrap/css/bootstrap.min.css" type="text/css">
  <link rel="stylesheet" href="<?php echo BOWER; ?>font-awesome/css/font-awesome.min.css" type="text/css">  
  <link rel="stylesheet" href="<?php echo CSS; ?>cor.css" type="text/css">
  <script src="<?php echo BOWER; ?>bootstrap/js/jquery.js"></script>
  <script src="<?php echo BOWER; ?>bootstrap/js/bootstrap.min.js"></script>
  <script src="<?php echo BOWER; ?>bootstrap/js/bootstrap-datepicker.js"></script>
  <script src="<?php echo BOWER; ?>bootstrap/js/bootstrap-datepicker.min.js"></script>
  <script src="<?php echo BOWER; ?>bootstrap/locales/bootstrap-datepicker.min.js"></script>
  <?php 
  echo $add_css;
  echo $add_js;
  ?>
</head>

<nav class="navbar navbar-inverse fundo-barra">
  <div class="container">


    <div class="navbar-header cor-barra">

      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="navbar-header navbar-left">
        <?php 
        $server = $_SERVER['SERVER_NAME'];

        $ok = $_SERVER ['REQUEST_URI'];
        $url = "http://" . $server . $ok;
        if($url === 'http://localhost/sistema/funcionario/login'){?>
        <a href="<?php  echo BASE . 'funcionario/login';?>">
          <img class="img-responsive" src="<?php echo IMG; ?>agplogo.png" alt="LOGO" width="180" height="170">
        </a>
        <?php
      }
      else{
        ?>
        <a href="<?php  echo BASE . 'funcionario/produto';?>">
          <img class="img-responsive" src="<?php echo IMG; ?>agplogo.png" alt="LOGO" width="180" height="170">
        </a>
        <?php
      }

      ?>

    </div>
  </div>
  <div class="col-sm-2">
  </div>
</div>
</nav>
</header>
<body>
