<!DOCTYPE html>
<html>

<head>

 
  <body>



    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">




    <!-- Bootstrap -->
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link href="css/Cor.css" rel="stylesheet">
    <link href="css/link.css" rel="stylesheet">



        <!-- The above 3 meta tags *must* come first in the head; any other head
        content must come *after* these tags -->
        <title>AGP Performance Shop - Página Administrativa</title>


        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media
        queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file://
      -->


      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>


    </head>

    <body>


      <section> 

        <!-- aside significa o canto superior Esquerdo-->
        <!-- Codigo da Barra de Categorias do Site-->
        <!-- Começo da Pagina, margim-top é o tamanho do espaço em relação ao borda da pagina-->
        <aside class="container">

          <?php echo (isset($this->alert) ? $this->alert : '');?>

          <div class="col-md-12">

            <ul class="nav nav-tabs nav-justified">
              <li class="active"><a href="<?php echo BASE; ?>funcionario/produto" data-toggle=""><div class="tab-cor">Produtos</div></a></li>
              <li><a href="<?php echo BASE; ?>funcionario/pedido" data-toggle=""><div class="tab-cor">Pedidos</div></a></li>
              <li><a href="<?php echo BASE; ?>funcionario/relatorio-vendas" ><div class="tab-cor">Relatório de Vendas</div></a></li>
            </ul>

            <div class="tab-content">

              <!-- TAB PRODUTOS-->
              <div class="tab-pane fade in active"  id="produtos">
                <br>
                <div class="panel panel-default">
                  <div class="panel-body">



                    <font size="6">
                     <!-- Mensagem -->
                     <center><b><p>Cadastro de Produtos</p></b></center>
                   </font>



                   <div class="col-md-2">
                    <ul class="nav nav-tab nav-stacked">

                     <li>

                      <?php 
                      if($view_departament):

                        foreach ($view_departament as $categoria) {                  

                          ?>


                          <a href="<?php echo BASE. 'funcionario/produto/'. $categoria->id; ?>">
                            <div class="tab-cor-font">
                              <?php echo $categoria->name_departament; ?>
                            </div>
                          </a>              
                          

                          <?php 
                        }
                        endif;
                        ?>


                      </li>  
                    </ul>
                  </div>




                  <div class="col-md-10">


                    <div class="tab-content">

                      <!-- TAB PROCESSADORES -->
                      <div class="tab-pane fade in active"  id="processador">
                       <div class="panel panel-default">
                        <div class="panel-body">

                          <font size="4">
                           <!-- Mensagem -->
                           
                         </font>
                         <?php if(isset($view_id_departament) && !empty($view_id_departament)){
                          $departament = $view_id_departament;
                        } 
                        else{
                          $departament = "";
                        }
                        ?>
                        <p>
                          <?php if(!isset($view_class) && empty($view_class)){ ?>
                          <a href="<?php echo BASE. "funcionario/cadastrar/". $departament; ?>"><button type="submit" class="btn btn-danger cor-botao">Adicionar Produto a Categoria</button></a>
                          <?php 
                        }
                        else{
                          echo '<div class="alert alert-danger"><strong>Atenção!</strong> Para Cadastrar um produto é necessário selecionar uma categoria. </div>';                   
                        }
                        ?>
                      </p>

                      <!-- Lista Pedidos -->
                      <div id="list" class="row">
                        <div class="table-responsive col-md-12">
                          <table class="table" cellspacing="0" cellpadding="0">

                            <thead>
                              <tr>
                                <th>Cod</th>
                                <th>Produto</th>
                                <th>Preço</th>
                                <th>Quantidade</th>
                                <th></th>
                              </tr>
                            </thead>

                            <tbody>
                              <?php 
                              if($view_produtos): 
                                foreach ($view_produtos as $produto) {


                                 ?>


                                 <tr>
                                  <td><?php echo $produto->id; ?></td>
                                  <td><a href="<?php echo BASE. 'produto/detalhes/'. $produto->id;?>"><?php echo $produto->name; ?></a></td>
                                  <td><?php echo $produto->price; ?></td>
                                  <td><?php echo $produto->stock; ?></td>
                                  <td class="actions">
                                    <a class="btn btn-default btn-xs cor-botao" href="<?php echo BASE. 'funcionario/zerar-produto/' . $produto->id; ?>">Remover do Estoque</a>
                                    <a class="btn btn-default btn-xs cor-botao" href="<?php echo BASE. 'funcionario/edita-produto/' . $produto->id; ?>">Editar</a>
                                  </td>
                                </td>
                              </tr>
                              <?php 
                            } 
                            endif;

                            ?>




                          </tbody>
                        </table>
                      </div>
                    </div> <!-- Lista Pedidos -->




                  </div>
                </div>
              </div>




            </aside>


          </section>




        </body>
        </html>