
<FORM name="agp" method="POST" action="<?php echo BASE;  ?>Login/logar" enctype="multipart/form-data">
  <aside class="container">

    <div class="col-md-12">     <?php echo (isset($this->alert) ? $this->alert : '')?>

      <div class="panel panel-default">
        <div class="panel-body">


          <center><p>

            <font size="6">
             <!-- Mensagem -->
             <b>Acessar a Minha conta</b>
           </font>

         </p></center>


         <div class="col-md-3">
         </div>


         <div class="col-md-6">


           <label for="inputEmail"><b>Email: *</b></label>
           <input  required  class="form-control" id="inputEmail" name="email" type="email" placeholder="Digite a sua Email..." value="<?php echo $this->request->post('email') ?>"  maxlength=50/>
  <br>
           <label for="inputSenha"><b>Senha: *</b></label>
           <input  required class="form-control" id="inputSenha" name="password" type="password" placeholder="Digite a sua senha..."  maxlength=30 />

           <p>

<br>
            <a href="<?php echo BASE;  ?>recuperar" class="link-cadastro-login">Não Lembro minha Senha</a> </p>
          </p>
          <p>
            <a href="<?php echo BASE;  ?>cadastro-cliente" class="link-cadastro-login">Não tenho Cadastro</a>
          </p>
          <p>
           <input value="Entrar" type="submit" class="btn btn-danger cor-botao" >
         </p>
       </div>


     </div>
   </div>



 </aside>
