  
<FORM name="agp" method="POST" action="<?php echo BASE;  ?>conta/editar-email" enctype="multipart/form-data">

 <aside class="container" style="margin-top:100px;">

  <?php echo (isset($this->alert) ? $this->alert : '')?>

  <div class="col-md-12">


    <div class="panel panel-default">
      <div class="panel-body">




      <center><p>

          <font size="6">
           <!-- Mensagem -->
           <b>Redefinir Email</b>
         </font>
       </p></center>



       <div class="col-md-4">

       </div>


       <div class="col-md-4">

        <label for="inputEmail"><b>Digite o Novo Email:</b></label>
        <input  required class="form-control" id="inputEmail" type="email" name="email" placeholder="SeuEmail@SeuEmail.com" value="<?php echo $this->request->post('email') ?>" maxlength="50">
        <label for="inputEmail2"><b>Digite o Email Novamente:</b></label>
        <input required  class="form-control" id="inputSenha2" type="email" name="confirmEmail" placeholder="SeuEmail@SeuEmail.com" value="<?php echo $this->request->post('confirmEmail') ?>" maxlength="50" />


        <br>
        <br>

        <center><button class="btn btn-danger btn-lg cor-botao">Redefinir</button> </center>


      </div>
    </div>
  </div>
</div>
</aside>




<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="js/jquery.js"></script>
        <!-- Include all compiled plugins (below), or include individual
        files as needed -->
        <script src="js/bootstrap.min.js"></script>

      </aside>

    </article>

  </section>

</FORM>
</body>
</html>