
<section>
  <FORM name="agp" method="POST" action="<?php echo BASE;  ?>endereco/cadastrar-endereco" enctype="multipart/form-data">
    <aside class="container">

      <?php echo (isset($this->alert) ? $this->alert : '')?>
      <div class="row">

        <div class="col-md-2">
        </div>
        <div class="col-md-2">
        </div>
        <div class="col-md-2">
        </div>
        <div class="col-md-2">
        </div>
        <div class="col-md-2">
        </div>
        <div class="col-md-2">

        </div>

      </div>

      <div class="col-sm-12">

        <ul class="nav nav-tab nav-justified">
         <li class="active"><a href="<?php echo BASE . 'conta/informacao'; ?>"><div class="tab-cor">Informações</div></a></li>
         <li><a href="<?php echo BASE . 'conta/endereco'; ?>"><div class="tab-cor">Endereços</div></a></li>
         <li><a href="<?php echo BASE . 'conta/pedido'; ?>"><div class="tab-cor">Pedidos</div></a></li>
       </ul>
       <br>
       <div class="panel panel-default">
        <div class="panel-body">

          <font size="6">
            <center><b>Endereços da Conta</b></center>
          </font>

          <br>

          <div class="col-md-3">
          </div>

          <div class="col-md-6">  

            <div class="form-group">



              <font size="3">
                <center><b>Endereços Cadastrados</b></center>
              </font>


              <label for="editarendereco">Endereço:</label>
              <input  required type="text" class="form-control" id="editarendereco" name="street" maxlength="50">

              <label for="editarnumero">Número:</label>
              <input required  type="number" style="max-width:80px;" class="form-control" id="editarnumero" name="number" max=99999>

              <label for="editarcomplemento">Complemento:</label>
              <input   type="text" style="max-width:320px;" class="form-control" id="editarcomplemento" name="complement" maxlength="50">

              <label for="editarbairro">Bairro:</label>
              <input  required type="text" style="max-width:320px;" class="form-control" id="editarbairro" name="neighbourhood" maxlength="50">

              <label for="editarcidade">Cidade:</label>
              <input  required type="text" style="max-width:250px;" class="form-control" id="editarcidade" name="city" maxlength="50">

              <label for="editarcidade">CEP:</label>
              <input required  type="number" style="max-width:150px;" class="form-control" id="editarcep" name="cep" max=99999999>

              <label for="editarestado">Estado:</label>
              <input required  type="text" style="max-width:150px;" class="form-control" id="editarcep" name="uf" maxlength="2">
  
  
              <br>
               <center>
                <input class="btn btn-default cor-botao" type="submit" aria-haspopup="true" aria-expanded="false" value="Adicionar Endereço ">         
                <a href="<?php echo BASE .'endereco/exibir-endereco';?>"><button type="button" class="btn btn-default cor-botao">Exibir endereços</button>
                </a>
              </center>
            </div> 
          </div>
          <div class="col-md-1">
        </div>
      </div>
    </div>
  </div>


    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="<?php echo BOWER; ?> bootstrap/dist/js/jquery.js"></script>
        <!-- Include all compiled plugins (below), or include individual
        files as needed -->
        <script src=" <?php echo BOWER; ?> bootstrap/dist/js/bootstrap.min.js"></script>



      </aside>


    </section>

  </FORM>


</body>
</html>