  
<FORM name="agp" method="POST" action="<?php echo BASE . 'recuperar/redefinir/'. $view_id;  ?>" enctype="multipart/form-data">

 <aside class="container" style="margin-top:100px;">

  <?php echo (isset($this->alert) ? $this->alert : '')?>

  <div class="col-md-12">


    <div class="panel panel-default">
      <div class="panel-body">




      <center><p>

          <font size="6">
           <!-- Mensagem -->
           <b>Redefinir Senha</b>
         </font>
       </p></center>



       <div class="col-md-4">

       </div>


       <div class="col-md-4">

        <label for="inputSenha"><b>Digite a Nova Senha:</b></label>
        <input  required class="form-control" id="inputSenha" maxlength="30" type="password" name="password" placeholder="Digite a sua Senha..." />
        <label for="inputSenha2"><b>Digite a Senha Novamente:</b></label>
        <input required  class="form-control" id="inputSenha2" type="password" maxlength="30" name="confirmpassword" placeholder="Digite Novamente..." />


        <br>
        <br>

        <center><button class="btn btn-danger btn-lg cor-botao">Mudar</button> </center>


      </div>
    </div>
  </div>
</div>
</aside>




<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="js/jquery.js"></script>
        <!-- Include all compiled plugins (below), or include individual
        files as needed -->
        <script src="js/bootstrap.min.js"></script>

      </aside>

    </article>

  </section>

</FORM>
</body>
</html>