





<!-- Começo do Codigo -->
<section> 

    <!-- aside significa o canto superior Esquerdo-->
    <!-- Codigo da Barra de Categorias do Site-->
    <!-- Começo da Pagina, margim-top é o tamanho do espaço em relação ao borda da pagina-->
    <aside>
        <div class="container">

            <!-- Divisão em 3 Colunas -->
            <aside class="col-md-3">


                <center><a href="<?php echo BASE . 'lista-produtos'; ?>" id="link_voltar"> <h3>Voltar a Loja</h3> </a></center>

                <div class="list-group">

                    <a class="list-group-item disabled"> Duvidas e Suporte:</a>
                    <a href="<?php echo BASE . 'estatico/entrega'; ?>" class="list-group-item">Entrega</a>
                    <a href="<?php echo BASE . 'estatico/formas-pagamento'; ?>" class="list-group-item">Formas de Pagamento</a>
                    <a href="<?php echo BASE . 'estatico/garantia'; ?>" class="list-group-item">Garantia</a>
                    <a href="<?php echo BASE . 'estatico/politica-privacidade'; ?>" class="list-group-item">Politica de Privacidade</a>
                    <a href="<?php echo BASE . 'estatico/troca'; ?>" class="list-group-item">Trocas e Devoluções</a>

                    
                </div>


            </aside>
            <!-- Fim da Barra de Categorias-->



            <!-- Inicio do painel Principal Central, onde é a Estrutura da pagina -->
            <div class="panel panel-default">

                <div class="panel-body">


                    <!-- Pulo de Linha-->
                    <p></p>


                    <!--Começo do Article, Canto direito da pagina -->
                    <!-- Divisão em 9 colunas-->

                    <article> 

                        <div class="col-md-9">

                            <h7>
                               <a href="<?php echo BASE . 'lista-produtos'; ?>" id="config-links-top">Home</a> &gt; <a href="<?php echo BASE . 'estatico/garantia'; ?>" id="config-links-top">Garantia</a>
                           </div>

                       </h7>


                       <p></p>
                       

                       <center><div class="cor-padrao-espec">GARANTIA</div></center>
                       <p></p>
                       <p></p>
                       <p></p>

                       <center><div class="cor-padrao-espec">Garantia Legal:</div></center>
                       <p>

                        <p></p>
                        <p></p>
                        <p></p>


                        <p></p>
                        <p></p>
                        <p></p>

                        <p>
                            Todos os produtos vendidos na pagina da AGP Performance Shop possuem garantia legal de 90 dias, contando a partir da data que o produto é recebido pelo cliente. Todos os produtos que apresentam defeitos produzidos por má utilização não são cobertos pela garantia legal da loja. Todos produtos devolvidos a loja passaram por analise técnica. Após o prazo de 90 dias, a responsabilidade sobre o funcionamento ou garantia e de total responsabilidade do fornecedor, sendo o cliente responsável por acionar esse serviço. 
                        </p>  
                    </div>


                </div>

            </article>

