





<!-- Começo do Codigo -->
<section> 

    <!-- aside significa o canto superior Esquerdo-->
    <!-- Codigo da Barra de Categorias do Site-->
    <!-- Começo da Pagina, margim-top é o tamanho do espaço em relação ao borda da pagina-->
    <aside>
        <div class="container">

            <!-- Divisão em 3 Colunas -->
            <aside class="col-md-3">


                <center><a href="<?php echo BASE . 'lista-produtos'; ?>" id="link_voltar"> <h3>Voltar a Loja</h3> </a></center>

                <div class="list-group">

                    <a class="list-group-item disabled"> Duvidas e Suporte:</a>
                    <a href="<?php echo BASE . 'estatico/entrega'; ?>" class="list-group-item">Entrega</a>
                    <a href="<?php echo BASE . 'estatico/formas-pagamento'; ?>" class="list-group-item">Formas de Pagamento</a>
                    <a href="<?php echo BASE . 'estatico/garantia'; ?>" class="list-group-item">Garantia</a>
                    <a href="<?php echo BASE . 'estatico/politica-privacidade'; ?>" class="list-group-item">Politica de Privacidade</a>
                    <a href="<?php echo BASE . 'estatico/troca'; ?>" class="list-group-item">Trocas e Devoluções</a>

                    
                </div>


            </aside>
            <!-- Fim da Barra de Categorias-->



            <!-- Inicio do painel Principal Central, onde é a Estrutura da pagina -->
            <div class="panel panel-default">

                <div class="panel-body">


                    <!-- Pulo de Linha-->
                    <p></p>


                    <!--Começo do Article, Canto direito da pagina -->
                    <!-- Divisão em 9 colunas-->

                    <article> 

                        <div class="col-md-9">

                            <h7>
                            <a href="<?php echo BASE . 'lista-produtos'; ?>" id="config-links-top">Home</a> &gt; <a href="<?php echo BASE . 'estatico/missao'; ?>" id="config-links-top">Missão, Visão e Valores</a>
                           </div>

                       </h7>


                       <p></p>


                       <center><div class="cor-padrao-espec">Missão, Visão e Valores</div></center>
                       <p></p>
                       <p></p>
                       <p></p>

                       <center><div class="cor-padrao-espec">Missão</div></center>
                       “Entregar os melhores Produtos e Marcas. Preço extremamente competitivo, em cada Produto oferecido na Loja, em relação as concorrentes do Mercado. ”
                       <br>
                       <center><div class="cor-padrao-espec">Visão</div></center>
                       “Ser o Referência no Negócio, como o maior Distribuidor e Revendedor do Mercado Brasileiro. ”
                       <br>
                       <br>
                       <center><div class="cor-padrao-espec">Valores</div></center>
                       O Maior Valor da empresa é Respeitar o Cliente, sempre oferecendo as Melhores Opções de Compra. Ter nossa loja como a Preferência do Cliente. ”
                       <br>
                       <br>
                   </div>


               </div>

           </article>
