

<!-- Começo do Codigo -->
<section> 

    <!-- aside significa o canto superior Esquerdo-->
    <!-- Codigo da Barra de Categorias do Site-->
    <!-- Começo da Pagina, margim-top é o tamanho do espaço em relação ao borda da pagina-->
    <aside>
        <div class="container">

            <!-- Divisão em 3 Colunas -->
            <aside class="col-md-3">


                <center><a href="<?php echo BASE . 'lista-produtos'; ?>" id="link_voltar"> <h3>Voltar a Loja</h3> </a></center>

                <div class="list-group">

                    <a class="list-group-item disabled"> Duvidas e Suporte:</a>
                    <a href="<?php echo BASE . 'estatico/entrega'; ?>" class="list-group-item">Entrega</a>
                    <a href="<?php echo BASE . 'estatico/formas-pagamento'; ?>" class="list-group-item">Formas de Pagamento</a>
                    <a href="<?php echo BASE . 'estatico/garantia'; ?>" class="list-group-item">Garantia</a>
                    <a href="<?php echo BASE . 'estatico/politica-privacidade'; ?>" class="list-group-item">Politica de Privacidade</a>
                    <a href="<?php echo BASE . 'estatico/troca'; ?>" class="list-group-item">Trocas e Devoluções</a>

                    
                </div>


            </aside>
            <!-- Fim da Barra de Categorias-->



            <!-- Inicio do painel Principal Central, onde é a Estrutura da pagina -->
            <div class="panel panel-default">

                <div class="panel-body">


                    <!-- Pulo de Linha-->
                    <p></p>


                    <!--Começo do Article, Canto direito da pagina -->
                    <!-- Divisão em 9 colunas-->

                    <article> 

                        <div class="col-md-9">

                            <h7>
                               <a href="<?php echo BASE . 'lista-produtos'; ?>" id="config-links-top">Home</a> &gt; <a href="<?php echo BASE . 'estatico/politica-privacidade'; ?>" id="config-links-top">Política de Privacidade</a>
                           </div>

                       </h7>


                       <p></p>
                       

                       <center><div class="cor-padrao-espec">POLÍTICA DE PRIVACIDADE</div></center>
                       <p></p>
                       <p></p>
                       <p></p>

                       <center><div class="cor-padrao-espec">Segurança Digital:</div></center>
                       <p>

                        <p></p>
                        <p></p>
                        <p></p>

                        O site da AGP Performance é completamente seguro, possuímos vários Protocolos para Segurança da Informação coletada de Todos os Nossos Clientes, desde Endereços até Dados de Cartões de Crédito...</p>


                        <p></p>
                        <p></p>
                        <p></p>
                        <p></p>
                        <p></p>
                        <p></p>

                        <center><div class="cor-padrao-espec">Política de Privacidade e Coleta de Dados:</div></center>

                        <p></p>
                        <p></p>
                        <p></p>

                        <p>
                            Todo o Usuário que Acessa, Compra ou Apenas Cria uma Conta, declara que Concorda com Nossos termos de uso e Termos de responsabilidade, todos os dados Coletados são Guardados de formas Extremamente Seguras Comforme Padrões de Segurança Digital. Esses Dados só podem ser Acessados por Terceiros em Dois Casos, Com a Autorização do Usuário, como Por Exemplo nosso Televendas. E por Ação Judicial, onde pode acessar mesmo não tendo a Autorização do Usuário. 
                        </p>  
                    </div>


                </div>

            </article>



            
