




<!-- Começo do Codigo -->
<section> 

    <!-- aside significa o canto superior Esquerdo-->
    <!-- Codigo da Barra de Categorias do Site-->
    <!-- Começo da Pagina, margim-top é o tamanho do espaço em relação ao borda da pagina-->
    <aside>
        <div class="container">

            <!-- Divisão em 3 Colunas -->
            <aside class="col-md-3">


                <center><a href="<?php echo BASE . 'lista-produtos'; ?>" id="link_voltar"> <h3>Voltar a Loja</h3> </a></center>

                <div class="list-group">

                    <a class="list-group-item disabled"> Duvidas e Suporte:</a>
                    <a href="<?php echo BASE . 'estatico/entrega'; ?>" class="list-group-item">Entrega</a>
                    <a href="<?php echo BASE . 'estatico/formas-pagamento'; ?>" class="list-group-item">Formas de Pagamento</a>
                    <a href="<?php echo BASE . 'estatico/garantia'; ?>" class="list-group-item">Garantia</a>
                    <a href="<?php echo BASE . 'estatico/politica-privacidade'; ?>" class="list-group-item">Politica de Privacidade</a>
                    <a href="<?php echo BASE . 'estatico/troca'; ?>" class="list-group-item">Trocas e Devoluções</a>

                    
                </div>


            </aside>
            <!-- Fim da Barra de Categorias-->



            <!-- Inicio do painel Principal Central, onde é a Estrutura da pagina -->
            <div class="panel panel-default">

                <div class="panel-body">


                    <!-- Pulo de Linha-->
                    <p></p>


                    <!--Começo do Article, Canto direito da pagina -->
                    <!-- Divisão em 9 colunas-->

                    <article> 

                        <div class="col-md-9">

                            <h7>
                             <a href="<?php echo BASE . 'lista-produtos'; ?>" id="config-links-top">Home</a> &gt; <a href="<?php echo BASE . 'estatico/quem-somos'; ?>" id="config-links-top">Quem Somos?</a>
                         </div>

                     </h7>


                     <p></p>
                     

                     <center><div class="cor-padrao-espec">Quem Somos?</div></center>
                     <p></p>
                     <p></p>
                     <p></p>


                     Fundada em 2016, a AGP Performance Shop é uma loja que trabalha com diversos produtos na comercialização de Hardware e Equipamentos de informática, sendo uma área que a cada dia está em constante avanço e crescimento comercial, onde qualidade, variedade e um preço baixo de produtos, acompanhado de um atendimento diferenciado fazem a diferença para total satisfação do cliente.
                     Possuímos nossa instalação situada em São Paulo/SP, entretanto realizamos vendas apenas pela internet, trazendo maior comodidade a nosso clientes vendendo num ambiente online. 

                 </div>


             </div>

         </article>
