

<!-- Começo do Codigo -->
<section> 

  <!-- aside significa o canto superior Esquerdo-->
  <!-- Codigo da Barra de Categorias do Site-->
  <!-- Começo da Pagina, margim-top é o tamanho do espaço em relação ao borda da pagina-->
  <aside>
    <div class="container">

      <!-- Divisão em 3 Colunas -->
      <aside class="col-md-3">


        <center><a href="<?php echo BASE . 'lista-produtos'; ?>" id="link_voltar"> <h3>Voltar a Loja</h3> </a></center>

        <div class="list-group">

          <a class="list-group-item disabled"> Duvidas e Suporte:</a>
          <a href="<?php echo BASE . 'estatico/entrega'; ?>" class="list-group-item">Entrega</a>
          <a href="<?php echo BASE . 'estatico/formas-pagamento'; ?>" class="list-group-item">Formas de Pagamento</a>
          <a href="<?php echo BASE . 'estatico/garantia'; ?>" class="list-group-item">Garantia</a>
          <a href="<?php echo BASE . 'estatico/politica-privacidade'; ?>" class="list-group-item">Politica de Privacidade</a>
          <a href="<?php echo BASE . 'estatico/troca'; ?>" class="list-group-item">Trocas e Devoluções</a>


        </div>


      </aside>
      <!-- Fim da Barra de Categorias-->



      <!-- Inicio do painel Principal Central, onde é a Estrutura da pagina -->
      <div class="panel panel-default">

        <div class="panel-body">


          <!-- Pulo de Linha-->
          <p></p>


          <!--Começo do Article, Canto direito da pagina -->
          <!-- Divisão em 9 colunas-->

          <article> 

            <div class="col-md-9">

              <h7>
              <a href="<?php echo BASE . 'lista-produtos'; ?>" id="config-links-top">Home</a> &gt; <a href="<?php echo BASE . 'estatico/troca'; ?>" id="config-links-top">Trocas e Devoluções</a>
             </div>

           </h7>


           <p></p>


           <center><div class="cor-padrao-espec">TROCAS E DEVOLUÇÕES</div></center>
           <p></p>
           <p></p>
           <p></p>

           O prazo para trocas é de 7 dias a partir da data de recebimento do Produto, onde serão aceitas trocas pelos seguintes motivos de defeito de fabricação. Para a devolução do produto, o cliente deverá enviar o produto da mesma forma que recebeu, com todo conteúdo da caixa, além disso ele deverá enviar a Nota fiscal que acompanha o Produto, o custo do envio e da embalagem para a devolução é de total responsabilidade dos clientes. Para devoluções por motivo de arrependimento, serão aceitas apenas para clientes que não violaram a caixa e já utilizaram o produto, ou seja, o produto deverá estar lacrado. O custo envio e da embalagem também será de responsabilidade dos clientes.
           <br>
           Trabalhamos apenas com trocas por produtos de mesmo modelo ou da mesma espécie ou devolução da quantia paga, com extorno para cartões e depósito em conta para compras com boletos bancários.

         </div>


       </div>

     </article>

