
</header>
<!-- Começo do Codigo -->

<section> 

  <!-- aside significa o canto superior Esquerdo-->
  <!-- Codigo da Barra de Categorias do Site-->
  <!-- Começo da Pagina, margim-top é o tamanho do espaço em relação ao borda da pagina-->
  <aside class="container">

   <div class="col-md-12">   
    <div class="panel panel-default">
      <div class="panel-body">

        <?php if(!isset($view_status)){
          if(!isset($view_pesquisa)){ ?>

          <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">

            <!-- Wrapper for slides -->
            <div class="carousel-inner" role="listbox">

              <div class="item active">
                <img src="<?php echo IMG; ?>slide1.png" alt="slide1">
              </div>

              <div class="item">
                <img src="<?php echo IMG; ?>slide2.png" alt="slide2">
              </div>

              <div class="item">
                <img src="<?php echo IMG; ?>slide3.png" alt="slide3">
              </div>

            </div>


            <!-- Controls -->
            <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
              <span class="glyphicon glyphicon-chevron-left cor-voltar" aria-hidden="true"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
              <span class="glyphicon glyphicon-chevron-right cor-avancar" aria-hidden="true"></span>
              <span class="sr-only">Next</span>
            </a>
          </div>

          <?php 
//remoção do carrosel caso o usuario clique em departamento e substituição pelos detalhes de cada produto ou "filtos da categoria"
        }
      }
      ?>



      <br>




      <!-- Divisão em 3 Colunas -->
      <aside class="col-md-3">

        <?php if(isset($view_status)){ 

          ?>

          <div class="list-group">

            <a class="list-group-item fonte-filtro fundo-filtro disabled"> Marca/Fabricante</a>

            <?php

            foreach ($view_marca as $m) {
             $marcas  = Supplier::find($m->supplier_id);
             $numero1 = 0;
             $sql_marca  =  'select * from products where supplier_id = '. $m->supplier_id. ' and departament_id = '. $view_depart->id ;
             $marcador = Product::find_by_sql($sql_marca);
             foreach ($marcador as $s) {
              $numero1++;
            }

            ?>         
            <a href="<?php 
            if(isset($view_observation) && !empty($view_observation)){ 
              echo BASE . 'lista-produtos/departamento/' . $view_depart->id .'/'. $marcas->id . '/'. $view_observation; 
            }
            else{ 
              echo BASE . 'lista-produtos/departamento/' . $view_depart->id .'/'. $marcas->id; 
            } 
            ?>" class="list-group-item fonte-filtro"><?php echo $marcas->name.' ('.$numero1.')'; ?></a>
            <?php  } ?>
            <br>
            <a class="list-group-item fonte-filtro fundo-filtro disabled"><?php echo $view_depart->observation_departament; ?></a>
            <?php foreach ($view_filter as $f) {
              $numero = 0;
              $sql_filter  =  'select * from products where filter = "'. $f->filter. '" and departament_id = '. $view_depart->id ;
              $contador = Product::find_by_sql($sql_filter);
              foreach ($contador as $c) {
                $numero++;
              }
              ?>         
              <a href="<?php 
              if(isset($view_observation) && !empty($view_observation)){ 
                echo BASE . 'lista-produtos/departament/' . $view_depart->id .'/'. urlencode($f->filter) . '/'. $view_observation; 
              }
              else{ 
                echo BASE . 'lista-produtos/departament/' . $view_depart->id .'/'. urlencode($f->filter); 
              } 
              ?>" class="list-group-item fonte-filtro"><?php echo $f->filter.' ('.$numero.')'; ?></a>
              <?php  } 
            }
            ?>
            <br>
            <div class="list-group">
              <a class="list-group-item disabled"> Categorias</a>
              <?php 

              foreach ($view_departament as $d) {
                ?>
                <a href="<?php echo BASE . 'lista-produtos/departamento/' . $d->id; ?>" class="list-group-item"><?php echo $d->name_departament ?> </a>

                <?php 
              }

              ?>

            </div>


            <div class="col-md-3">
              <br>
              <br>
              <br>
              <br>
              <br>
              <br>
              <br>
              <br>
              <br>
              <br>
              <br>
              <br>
              <br>
              <br>
              <br>
              <br>
              <br>
              <br>
              <br>
              <br>
              <br>
              <br>
              <br>

            </div>


          </aside>


          <div class="col-md-9">


            <h7>
              <!-- Links de Categorias-->
              <a href="<?php echo BASE . 'lista-produtos'; ?>" id="config-links-top">Home</a> > <?php if(isset($view_depart) && !empty($view_depart)){ ?>  <a href="<?php echo BASE . 'lista-produtos/departamento/' . $view_depart->id ; ?>" id="config-links-top"><?php echo $view_depart->name_departament; ?></a> > <?php  }  ?>

            </h7>

            <br>
            <br>

            <font size="6">
              <!-- Mensagem -->
              <?php if(!isset($view_depart)){ 
                if(isset($view_pesquisa)){
                  if(!isset($view_resultado)){
                    echo 'Resultados para: "' . $view_pesquisa.'"';;
                  }
                  else{
                    echo 'Nenhum resultado encontrado para: "' . $view_pesquisa.'"';;
                  }
                } else{



                  ?>

                  <b>Bem Vindo a AGP Performance</b>

                  <?php 
                }
              }
              else{
                echo "<b>Filtro por  $view_depart->name_departament</b>";
              }
              ?>
            </font>

            <br>


            <ul class="nav nav-pills">


              <!-- Listagem Dropdown -->
              <li class="dropdown ">

                <a class="dropdown-toggle cor-filtro" data-toggle="dropdown" href="#">

                  <!-- Titulo Dropdown -->
                  Filtrar Como...

                  <b class="caret"></b>

                </a>


                <!-- Menu do Dropdown -->
                <ul class="dropdown-menu">
                  <?php 

                  $server = $_SERVER['SERVER_NAME'];

                  $ok = $_SERVER ['REQUEST_URI'];
                  $url = "http://" . $server . $ok;

                  if($_SERVER['REQUEST_URI'] === '/sistema/lista-produtos' or $_SERVER['REQUEST_URI'] === '/sistema/lista-produtos/'){
                    ?>

                    <li>
                      <!-- Primeiro Item do Menu -->
                      <a href="<?php echo BASE . 'lista-produtos/lista/?'. "&filtro=price&parametro=asc"; ?>">Menor Preço</a>
                    </li>

                    <li>
                      <!-- Segundo Item do Menu -->
                      <a href="<?php echo BASE . 'lista-produtos/lista/?'. "&filtro=price&parametro=desc"; ?>">Maior Preço</a>
                    </li>

                    <li>
                      <!-- Terceiro Item do Menu -->
                      <a href="<?php echo BASE . 'lista-produtos/lista/?'. "&filtro=name&parametro=desc"; ?>">Nome (Z - A)</a>
                    </li>

                    <li>
                      <!-- Quarto Item do Menu -->
                      <a href="<?php echo BASE . 'lista-produtos/lista/?'. "&filtro=name&parametro=asc"; ?>">Nome (A - Z)</a>
                    </li>


                    <?php 
                  }
                  else{
                    if(isset($view_pesquisa)){
                      ?>


                      <li>
                        <!-- Primeiro Item do Menu -->
                        <a href="<?php echo $url. "&filtro=price&parametro=asc"; ?>">Menor Preço</a>
                      </li>

                      <li>
                        <!-- Segundo Item do Menu -->
                        <a href="<?php echo $url . "&filtro=price&parametro=desc"; ?>">Maior Preço</a>
                      </li>

                      <li>
                        <!-- Terceiro Item do Menu -->
                        <a href="<?php echo $url. "&filtro=name&parametro=desc"; ?>">Nome (Z - A)</a>
                      </li>

                      <li>
                        <!-- Quarto Item do Menu -->
                        <a href="<?php echo $url. "&filtro=name&parametro=asc"; ?>">Nome (A - Z)</a>
                      </li>
                      <?php 
                    }
                    else{
                      ?>
                        <li>
                        <!-- Primeiro Item do Menu -->
                        <a href="<?php echo $url. "/?filtro=price&parametro=asc"; ?>">Menor Preço</a>
                      </li>

                      <li>
                        <!-- Segundo Item do Menu -->
                        <a href="<?php echo $url . "/?filtro=price&parametro=desc"; ?>">Maior Preço</a>
                      </li>

                      <li>
                        <!-- Terceiro Item do Menu -->
                        <a href="<?php echo $url. "/?filtro=name&parametro=desc"; ?>">Nome (Z - A)</a>
                      </li>

                      <li>
                        <!-- Quarto Item do Menu -->
                        <a href="<?php echo $url. "/?filtro=name&parametro=asc"; ?>">Nome (A - Z)</a>
                      </li>
                      <?php 
                    }
                  }
                  ?>
                </ul>
              </li>
            </ul>


            <!-- Opções de Filtragem com Dropdown da Lista -->


            <br>

            <?php 
            foreach ($view_produto as $p) {
             ?>

             <!-- PRODUTO NA LISTA -->
             <div class="col-md-4 ">
              <a href="<?php echo BASE . 'produto/detalhes/' . $p->id; ?>" id="links-lista">
                <div class="panel panel-default selecao-produto-lista">
                  <div class="panel-body"><center><img style="max-height:94px;" class="img-responsive" min-width="210" min-height="110" src="<?php echo IMG .'products'. DS . $p->img1 ; ?>" alt="imgprincipal"></center></div>              
                  <div class="panel-footer">
                    <center><?php echo $p->name; ?></center>
                    <h4> <span class="label label-default cor-label"><?php if($p->stock < 1){ echo "Produto Indisponível";}else{ ?>Preço: 
                      R$<?php $preco = $p->price; 
                      $preco = number_format($preco, 2, ',', '');
                      echo $preco;
                    }
                    ?>                    
                  </span> </h4>
                </div>
              </div>
            </div></a>
            <!-- PRODUTO NA LISTA -->

            <?php  
          } 
          ?>

        </div>
      </div>

    </div>






    <!-- Parte superior da Lista-->
    <article>




    </aside>

  </article>

