    </header>
    <!-- Começo do Codigo -->

    <section>  

      <!-- aside significa o canto superior Esquerdo-->
      <!-- Codigo da Barra de Categorias do Site-->
      <!-- Começo da Pagina, margim-top é o tamanho do espaço em relação ao borda da pagina-->
      <aside class="container">

        <div class="row">

          <div class="col-md-2">
          </div>
          <div class="col-md-2">
          </div>
          <div class="col-md-2">
          </div>
          <div class="col-md-2">
          </div>
          <div class="col-md-2">
          </div>
          <div class="col-md-2">         
          </div>

        </div>


        <div class="panel panel-default">
          <div class="panel-body">




            <!-- Divisão em 3 Colunas -->
            <aside class="col-md-3">


              <div class="list-group">
                <a class="list-group-item disabled"> Categorias</a>
                <?php 

                foreach ($view_departament as $d) {
                  ?>
                  <a href="<?php echo BASE . 'lista-produtos/departamento/' . $d->id; ?>" class="list-group-item"><?php echo $d->name_departament ?> </a>

                  <?php 
                }

                ?>

              </div>

            </aside>



            <!-- Parte superior da Lista-->
            <article>


              <div class="col-md-9">


                <h7>
                  <!-- Links de Categorias-->
                  <a href="<?php echo BASE . 'lista-produtos'; ?>" id="config-links-top">Home</a> > <a href="<?php echo BASE . 'lista-produtos/departamento/' . $view_dep->id; ?>" id="config-links-top"><?php echo $view_dep->name_departament; ?></a> > <a href="<?php echo BASE . 'produto/detalhes/' . $view_produto->id; ?>" id="config-links-top"> <?php echo $view_produto->name; ?></a>

                </h7>

                <br>
                <br>

                <font size="5">
                  <!-- Titulo -->
                  <b><?php echo $view_produto->name; ?></b>
                </font>

                <br>
                <br>



                <div class="col-md-7">
                  <img class="img-responsive" src="<?php echo IMG . 'products' . DS . $view_produto->img1; ?>" alt="IMG">
                  <br>
                  <button type="button" class="btn btn-default btn-xs cor-botao" data-toggle="modal" data-target="#galeria">
                    Galeria de Imagens
                  </button>
                </div>

                <div class="col-md-5">

                 <br>
                 <?php if($view_produto->stock !== 0){ ?>
                 <font size="5">
                  <b>Preço:</b>
                </font>

                <font size="5">
                  <b>R$<?php $preco = $view_produto->price; 
                    $preco = number_format($preco, 2, ',', '.');
                    echo $preco;

                    ?></b>
                  </font>

                  <br>

                  <font size="2">
                    Ou em até 12x de R$ <?php $parcela = $view_produto->price / 12; 
                    $parcela = number_format($parcela, 2, ',', '.');
                    echo $parcela;

                    ?> S/ Juros*
                  </font>

                  <br>
                  <br>

                  <font size="2">
                    Unidade:
                  </font>

                  <br>
                  <form action="<?php echo BASE . 'carrinho/adicionar-item/' . $view_produto->id; ?>" method="post">
                    <input type="number" class="form-control" name="amount" style="max-width:100px;" value="1" min='1' max="<?php echo $view_produto->stock; ?>">
                    <br>
                    <input type="submit" class="btn btn-danger btn-lg cor-botao" value='Comprar'>
                  </form>
                  <?php }
                  else{
                    echo '<br><br><center><font size="4"><b>   PRODUTO INDISPONÍVEL </b></font></center>';
                  } 

                  ?>
                </div>

              </div>


              <!-- DESCRIÇÃO -->
              <div class="col-md-9">
                <br>

                <div class="panel panel-default">
                  <div class="panel-body">


                    <center><div class="cor-padrao-espec-titulo"><b><font size="3"> Especificações do Produto</font></b></div> </center>
                    <br>

                    <?php echo $view_produto->description; ?>

                  </div>
                </div>
              </div>
              <!-- DESCRIÇÃO -->




              <!-- Avaliações do produto -->
              <div class="col-md-12">

                <font size="4">
                  <center><b>Avaliação do Produto</b></center>
                </font>

                <br>



                <br>
                <?php if(isset($view_avaliacao) && !empty($view_avaliacao)){
                  $avaliacao = $view_avaliacao;
                  $avaliacao_otima = 0;
                  $avaliacao_regular = 0;
                  $avaliacao_pessimo = 0;

                  foreach ($avaliacao as $ava) {
                    if($ava->note === "Otimo"){
                      $avaliacao_otima++;
                    }
                    if($ava->note === "Regular"){
                      $avaliacao_regular++;
                    }
                    if($ava->note === "Pessimo"){
                      $avaliacao_pessimo++;
                    }
                  }
                  ?>
                  <div class="panel panel-default cor-padrao-fixa">
                    <div class="panel-heading">Total de Avaliações: <?php echo $avaliacao_otima + $avaliacao_regular + $avaliacao_pessimo; ?></div>
                    <div class="panel-body cinza-claro">
                      <?php echo $avaliacao_otima; ?> Avaliações como "Ótimo"
                    </div>
                    <div class="panel-body cinza-claro">
                     <?php echo $avaliacao_regular; ?> Avaliações como "Regular"
                   </div>
                   <div class="panel-body cinza-claro">
                     <?php echo $avaliacao_pessimo; ?> Avaliações como "Péssimo"
                   </div>
                 </div>
                 <?php 
               }
               else{
                ?>
                <div class="panel panel-default cor-padrao-fixa">
                  <div class="panel-heading">Total de Avaliações: 0 </div>
                  <div class="panel-body cinza-claro">
                    0 Avaliações como "Ótimo"
                  </div>
                  <div class="panel-body cinza-claro">
                   0 Avaliações como "Regular"
                 </div>
                 <div class="panel-body cinza-claro">
                   0 Avaliações como "Péssimo"
                 </div>
               </div>
               <?php 
             }
             ?>
             <?php if(isset($view_avaliacao) && !empty($view_avaliacao)){
              foreach ($view_avaliacao as $a) {
                  # code...

                ?>

                <div class="panel panel-default cor-padrao-fixa">

                  <div class="panel-heading ">Avaliado por <?php $u = User::find($a->user_id); 
                    echo $u->name; 
                    ?></div>


                    <div class="panel-body cinza-claro">

                      <div class="container-fluid">
                        <?php echo $a->message; ?>
                      </div>

                    </div>

                  </div>

                  <?php 
                }
              } 
              ?>


              <!-- Avaliações do produto -->


              <!-- MODAL GALERIA DE IMAGENS -->
              <div class="modal fade" id="galeria" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                <div class="modal-dialog" role="document">
                  <div class="modal-content">
                    <div class="modal-header">
                      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                      <h4 class="modal-title" id="myModalLabel">Galeria de Imagens</h4>
                    </div>
                    <div class="modal-body">





                      <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">

                        <!-- Wrapper for slides -->
                        <div class="carousel-inner" role="listbox">
                          <div class="item active">
                            <img class="img-responsive" src="<?php echo IMG . 'products' . DS . $view_produto->img1; ?>" alt="IMG">
                          </div>


                          <div class="item">
                            <img class="img-responsive" src="<?php echo IMG . 'products' . DS . $view_produto->img2; ?>" alt="IMG2">
                          </div>


                          <div class="item">
                            <img class="img-responsive" src="<?php echo IMG . 'products' . DS . $view_produto->img3; ?>" alt="IMG3">
                          </div>


                          <!-- Controls -->
                          <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
                            <span class="glyphicon glyphicon-chevron-left cor-voltar" aria-hidden="true"></span>
                            <span class="sr-only">Previous</span>
                          </a>
                          <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
                            <span class="glyphicon glyphicon-chevron-right cor-avancar" aria-hidden="true"></span>
                            <span class="sr-only">Next</span>
                          </a>
                        </div>
                      </div>





                    </div>
                  </div>
                </div>
              </div>
              <!-- MODAL GALERIA DE IMAGENS -->



            </div>

          </div>






        </aside>

      </article>

